name: Build

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node:
          - 12
          - 16

        target:
          - runs-on: windows-latest
            platform: windows
          - runs-on: ubuntu-latest
            platform: linux
          - runs-on: macos-latest
            platform: darwin

    runs-on: ${{ matrix.target.runs-on }}

    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Prepare
        run: bash .github/workflows/prepare.sh

      - name: Install
        run: |
          curl -o $RUNNER_TEMP/yarn.cjs https://repo.yarnpkg.com/3.2.0/packages/yarnpkg-cli/bin/yarn.js
          node $RUNNER_TEMP/yarn.cjs install --no-immutable

      - id: release
        name: Get latest release
        run: >
          echo ::set-output name=data::$(
            curl
            -H "Accept: application/vnd.github.v3+json"
            -H "Authorization: token ${{ secrets.WORKFLOW_TOKEN }}"
            https://api.github.com/repos/${{ github.repository }}/releases/latest
          )

      - name: Create release
        uses: koishijs/action-release@latest
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Upload
        run: >
          curl
          -X POST
          -H "Accept: application/vnd.github.v3+json"
          -H "Authorization: token ${{ secrets.WORKFLOW_TOKEN }}"
          -H "Content-Type: application/zip"
          ${{ steps.release.output.data.upload_url }}?name=${{ steps.release.output.data.tag_name }}-${{ matrix.target.platform }}-x64-node${{ matrix.node }}.zip
          --data-binary @$RUNNER_TEMP/bundle.zip
