name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - runs-on: windows-latest
            platform: windows
          - runs-on: ubuntu-latest
            platform: linux
          - runs-on: macos-latest
            platform: darwin

    runs-on: ${{ matrix.target.runs-on }}

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Set up yarn
        run: |
          curl -o $RUNNER_TEMP/yarn.cjs https://repo.yarnpkg.com/3.2.0/packages/yarnpkg-cli/bin/yarn.js
          echo 'nodeLinker: node-modules' > .yarnrc.yml
          sed -i package.json -e 's/\^//g'

      - name: Install
        run: node $RUNNER_TEMP/yarn.cjs install --no-immutable

      - name: Create release
        uses: koishijs/action-release@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
