name: Build

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - runs-on: windows-latest
            platform: windows
            output-arch: amd64
            node-arch: x64
          - runs-on: ubuntu-latest
            platform: linux
            output-arch: amd64
            node-arch: x64
          - runs-on: ubuntu-latest
            platform: linux
            output-arch: arm64
            node-arch: arm64
          - runs-on: ubuntu-latest
            platform: linux
            output-arch: armv7l
            node-arch: armv7l
          - runs-on: macos-latest
            platform: darwin
            output-arch: amd64
            node-arch: x64

    runs-on: ${{ matrix.target.runs-on }}

    steps:
      - name: Set up variables
        id: vars
        shell: bash
        run: |
          echo "NODE_VERSION=${{ matrix.target.node || '20' }}" >> $GITHUB_OUTPUT

      - name: Set up qemu and binfmt
        uses: docker/setup-qemu-action@v3

      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.vars.outputs.NODE_VERSION }}
          architecture: ${{ matrix.target.node-arch }}

      - name: Install zip (for windows)
        if: ${{ matrix.target.platform == 'windows' }}
        run: choco install zip

      - name: Prepare
        run: bash .github/workflows/prepare.sh

      - name: Install dependencies
        run: |
          yarn --no-immutable

      - name: Pack file
        run: bash .github/workflows/pack.sh

      - name: Upload asset
        shell: bash
        run: >
          bash .github/workflows/upload.sh
          '${{ matrix.target.platform }}-${{ matrix.target.output-arch }}-node${{ steps.vars.outputs.NODE_VERSION }}'
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Trigger docker build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        if: ${{ env.DOCKER_USERNAME != null }}
        run: gh workflow run Docker
