name: Tag

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: version
        name: Check version
        run: bash .github/workflows/version.sh

      - name: Create release
        if: ${{ steps.version.outputs.tag }}
        run: >
          curl
          -X POST
          -H "Accept: application/vnd.github.v3+json"
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          https://api.github.com/repos/${{ github.repository }}/releases
          -d '{
            "tag_name": "${{ steps.version.outputs.tag }}",
            "target_commitish": "${{ github.sha }}",
            "name": "${{ steps.version.outputs.tag }}"
          }'

      - name: Trigger build
        if: ${{ steps.version.outputs.tag }}
        run: >
          curl
          -X POST
          -H "Accept: application/vnd.github.v3+json"
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches
          -d '{
            "ref": "${{ github.ref }}"
          }'
